### ISSUE TITLE
make dashboardHeader()

### ISSUE THREAD

**Issue by cabaceo** [cabaceo/RCoreUI#2]
Port CoreUI's [header section](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/Static_Full_Project_GULP/index.html) into a R function dashboardHeader(). 

See [example](https://github.com/cabaceo/RCoreUI/blob/master/R/dashboardHeader.R).

**Comment by cabaceo** [comment]
@sliu102 Saw you pushed code. Is it done or are you still working on it? Please comment on this thread after finishing every major work so that I know and can check out your code. Also, please also comment if you encounter questions. Leo and I can help.

**Comment by sliu102** [comment]
Yes, I have some questions. Can you explain the function of deps.R. My code
was translating html to R just like LTE did, but has not CSS style.

**Comment by cabaceo** [comment]
My guess is that deps.R will look for those css and js files when invoked. I guess that based on reading the code. We'll find out after we implement some basic elements such as the header. Yes, I think you just need to translating html to R for the header. If you're done, I'll take it from here.

**Comment by sliu102** [comment]
I have translated html to R. But I when I add html dependencies in R
packages, it doesn't work. If we can solve this problem, the progress will
go much faster.

**Comment by sliu102** [comment]
Example:

doesn't work:
tags$html(tags$head(tags$link(href="inst/CoreUI/css/style.css",rel="stylesheet",
type="text/css")))

work:
  tags$style(".app-header.navbar {
  position: relative;
  flex-direction: row;
  height: 55px;
  margin: 0;
  padding: 0;
  background-color: #fff;
  border-bottom: 1px solid #cfd8dc; }")

**Comment by cabaceo** [comment]
Nice! At least something is working. That's promising. Don't be daunted. After we finish this project, we'll learn a lot. I'll take a look and let you know.

**Comment by cabaceo** [comment]
This is more involved than I expected. I've written the header, body and page functions and access the css and js using functions in dep.R, it's working, but just doesn't display correctly. Will need to investigate why.

**Comment by sliu102** [comment]
Cool. I'll try your code first！

**Comment by cabaceo** [comment]
I haven't pushed. Will do so after I make it work.

**Comment by cabaceo** [comment]
The problem is shiny uses Bootstrap 3 but CoreUI is based on Bootstrap 4.

**Comment by cowfox** [comment]
Is there any compatibility issue when using B4 instead of B3? 

To my understanding, the major diff. between B4 and B3 would be much more towards JS part and CSS part, not the R part?

**Comment by cabaceo** [comment]
This is my understanding. 

See [bootstrapLib](https://github.com/rstudio/shiny/blob/master/R/bootstrap.R) for how shiny finds the css and js of bootstrap 3. 

Then [dep.R](https://github.com/rstudio/shinydashboard/blob/master/R/deps.R) for how shinydashboard finds the css and js of AdminLTE.

The shinydashboard pkg then calls shiny::bootstrapPage(content, title = title) to load all those css and js files. [Source](https://github.com/rstudio/shinydashboard/blob/master/R/dashboardPage.R)

Now, what I did was to copy both the css and js files of bootstrap4 and CoreUI under our own [/inst](https://github.com/cabaceo/RCoreUI/tree/master/inst) and wrote similar [functions](https://github.com/cabaceo/RCoreUI/blob/master/R/bootstrap.R). They work, but don't show anything close to what CoreUI shows.

**Comment by cowfox** [comment]
Could you please help check the followings: 

- When a html page created, can you double check its source code to see the CSS and JS are loaded from your customized location, not the default? 
- If there a way to debug this part in R to see how it actually works? 

----

PS: How to set up the dev env. in a local machine?

**Comment by cabaceo** [comment]
half working now. Can find paths to CoreUI css and js files. But still cannot find paths to bootstrap4 css and js files.

**Comment by cabaceo** [comment]
File load/import are done. 
Will open a new issue for customizing css and etc.
