### ISSUE TITLE
re-clone RcoreUI

### ISSUE THREAD

**Issue by cabaceo** [cabaceo/RCoreUI#3]
@sliu102 I saw you still keep your original CoreUI/R/file. This is confusing and in conflict with how I set up the entire project folder structure. To improve, please delete the entire project on your local machine and re-clone the RcoreUI repo.

**Comment by sliu102** [comment]
Ok, I will do it as soon as I back to Chicago.

**Comment by cabaceo** [comment]
Shuxiao took a job in ShenZhen. Best wishes.
