### ISSUE TITLE
css edit

### ISSUE THREAD

**Issue by cabaceo** [cabaceo/RCoreUI#4]
There're conflicts between the style of shiny and that of CoreUI. For example, font size, sidebar hidden button and etc. We need to edit the css files to resolve.

**Comment by sliu102** [comment]
Ok, let's do it

**Comment by cabaceo** [comment]
@cowfox, you can let @sliu102 help you if needed. He has experiences in html and css.

**Comment by cabaceo** [comment]
Use these shortcuts in Rstudio to improve workflow:

* **Ctrl/Cmd + Shift + L** (skips install and loads the functions of the package you're developing directly into memory). You'll use this a lot as you'll need to constantly test the functions you write.
* **Ctrl/Cmd + Shift + D** (generates documents by converting roxygen comments to .Rd files). You'll probably use this less frequently.
* **Ctrl/Cmd + Shift + B** (completely rebuilds the package, including updating all the documentation, installs it in your regular library, then restarts R and reloads your package). You'll also use this one quite often. NOTE: This shortcut does not build vignettes to save time. Use devtools::build() to create a package bundle with vignettes included. 
* **Ctrl/Cmd + Shift + T** (test your package). Before using it, you need to first set up your pkg to use testthat by running `devtools::use_testthat()` in Rstudio.
* **Ctrl/Cmd + Shift + E** (automatically checks your pkg for common problems). Equivalent to `R CMD check` but better.

**Comment by cabaceo** [comment]
[Click](http://adv-r.had.co.nz/dsl.html) to understand how to use R to generate HTML and other DSL (eg: SQL, Latex)

**Comment by cabaceo** [comment]
Leo finished this. Excellent!
