### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by arugragh** [cabaceo/RCoreUI#8]
Hello, 
When i try "npm install" i get error.
log:
19929 warn r-core-ui@0.6.6 No repository field.
19930 warn r-core-ui@0.6.6 No license field.
19931 warn The package gulp is included as both a dev and production dependency.
19932 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
19933 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
19934 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
19934 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
19934 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
19934 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
19935 verbose stack Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
19935 verbose stack Exit status 1
19935 verbose stack     at EventEmitter.<anonymous> (/home/ANT.AMAZON.COM/arugragh/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
19935 verbose stack     at EventEmitter.emit (events.js:305:20)
19935 verbose stack     at ChildProcess.<anonymous> (/home/ANT.AMAZON.COM/arugragh/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
19935 verbose stack     at ChildProcess.emit (events.js:305:20)
19935 verbose stack     at maybeClose (internal/child_process.js:1028:16)
19935 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
19936 verbose pkgid node-sass@3.13.1
19937 verbose cwd /home/ANT.AMAZON.COM/arugragh/Desktop/RCoreUI-master
19938 verbose Linux 5.3.0-24-generic
19939 verbose argv "/home/ANT.AMAZON.COM/arugragh/.nvm/versions/node/v13.5.0/bin/node" "/home/ANT.AMAZON.COM/arugragh/.nvm/versions/node/v13.5.0/bin/npm" "install"
19940 verbose node v13.5.0
19941 verbose npm  v6.13.4
19942 error code ELIFECYCLE
19943 error errno 1
19944 error node-sass@3.13.1 postinstall: `node scripts/build.js`
19944 error Exit status 1
19945 error Failed at the node-sass@3.13.1 postinstall script.
19945 error This is probably not a problem with npm. There is likely additional logging output above.
19946 verbose exit [ 1, true ]

my node version - v13.5.0
npm version - 6.13.4

**Comment by gmlang** [comment]
We stopped active development a while back. Sorry for the inconvenience.

**Comment by arugragh** [comment]
Thanks for the quick response.
